apiVersion: pipecd.dev/v1beta1
kind: Application
spec:
  name: orders-kafka
  labels:
    team: platform
  plugins:
    kafka:
      topicsDir: topics
      schemasDir: schemas
      ownership:
        - orders
        - payments
      defaults:
        replicationFactor: 1
  pipeline:
    stages:
      - name: KAFKA_PLAN
      - name: KAFKA_REGISTER_SCHEMA
      - name: KAFKA_APPLY
